#!/bin/sh

echo
echo "*****************************************"
echo "*         Uninstall SimpleZOOMPanel     *"
echo "*****************************************"
EXTDIR="/usr/lib/enigma2/python/Plugins/Extensions/SimpleZOOMPanel"
dream='/var/lib/dpkg/info'

if [ -d "$dream" ]; then
   rm -rf "$EXTDIR" > /dev/null 2>&1
fi

if [ -d "$EXTDIR" ]; then
   rm -rf "$EXTDIR" > /dev/null 2>&1
fi
echo "*****************************************"
echo "*          ....done                     *"
echo "*****************************************"
exit 0


